# Generated by Django 3.2.9 on 2024-03-03 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_todo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
