# Generated by Django 4.2.10 on 2024-04-05 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='emp_Time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
