# Generated by Django 4.2.10 on 2024-04-05 17:37

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_todo_emp_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='emp_date',
            field=models.DateField(default=app.models.get_default_start_date),
        ),
    ]
