# Generated by Django 4.2.10 on 2024-04-05 17:52

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_todo_emp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='compare_date',
            field=models.DateField(default=app.models.get_default_start_date),
        ),
        migrations.AddField(
            model_name='todo',
            name='compare_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
