# Generated by Django 4.2.10 on 2024-04-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_todo_compare_date_todo_compare_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='emp_Time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='emp_date',
            field=models.DateField(null=True),
        ),
    ]
