# Generated by Django 4.2.10 on 2024-11-24 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_employeee_pircture_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='taskDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employeee_pircture'),
        ),
    ]
