# Generated by Django 4.2.10 on 2024-11-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_todo_taskdesc_alter_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='taskDesc',
            field=models.TextField(default='none', null=True),
        ),
    ]
