# Generated by Django 4.2.10 on 2024-11-24 09:03

import app.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_alter_todo_taskdesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='taskDesc',
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('taskDesc', models.TextField(default='none', null=True)),
                ('date', models.DateField()),
                ('Time', models.TimeField(default=datetime.time(12, 0))),
                ('status', models.BooleanField(default=False)),
                ('emp_date', models.DateField(null=True)),
                ('emp_Time', models.TimeField(null=True)),
                ('compare_date', models.DateField(default=app.models.get_default_start_date)),
                ('compare_time', models.TimeField(default=datetime.time(12, 0))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employeee_pircture')),
            ],
        ),
    ]
