# Generated by Django 4.2.10 on 2024-11-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
