# Generated by Django 4.2.10 on 2024-11-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Todo',
        ),
    ]
