# Generated by Django 4.2.10 on 2024-12-04 16:09

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Time',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='compare_time',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='emp_Time',
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(default=app.models.get_default_start_date),
        ),
        migrations.AlterField(
            model_name='todo',
            name='emp_date',
            field=models.DateField(default=app.models.get_default_start_date),
        ),
    ]
