# Generated by Django 4.2.10 on 2024-12-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_managerprofile_employeeprofile_alter_todo_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Managerprofile',
        ),
    ]
