# Generated by Django 4.2.10 on 2024-12-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_employeeprofile_profile_delete_managerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='status',
            new_name='position',
        ),
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profilename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
