# Generated by Django 4.2.10 on 2024-12-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_status_profile_position_profile_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
