# Generated by Django 4.2.10 on 2024-12-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='file',
        ),
    ]
