# Generated by Django 4.2.10 on 2024-12-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_profile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(default=1, upload_to='file/'),
            preserve_default=False,
        ),
    ]
