# Generated by Django 4.2.10 on 2024-12-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='compare_date',
        ),
    ]
