# Generated by Django 4.2.10 on 2024-12-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_todo_compare_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='file',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
