# Generated by Django 4.2.10 on 2025-01-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_todo_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='adminfiles',
            field=models.FileField(default=1, upload_to='admin-documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='file',
            field=models.FileField(upload_to='submitted-documents/'),
        ),
    ]
