# Generated by Django 4.2.10 on 2025-01-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_todo_adminfiles_alter_todo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='adminfiles',
            field=models.FileField(null=True, upload_to='admin-documents/'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='file',
            field=models.FileField(null=True, upload_to='submitted-documents/'),
        ),
    ]
